import { AssistantId, defaultAssistantId, resolveAssistantId } from './assistants';
import { SupportedLanguage, supportedLanguages } from './languages';
import type { WorldId } from './worlds';

type ThoughtSource = {
  openings: string[];
  endings: string[];
};

type CharacterThoughtSources = Record<SupportedLanguage, ThoughtSource>;

const thoughtSources: Record<AssistantId, CharacterThoughtSources> = {
  studyTroll: {
    en: {
      openings: [
        'The wing is open, accelerate now',
        'The crowd feels your first touch',
        'Cut inside and trust the next letter',
        'A brave dribble starts with one card',
        'This prompt is asking for pace',
        'The defender blinked, take the lane',
        'Your answer is already sprinting',
        'The right flank has space today',
        'A young star never waits too long',
        'The match wants a bold touch',
      ],
      endings: [
        'First touch, then sprint.',
        'Hit the gap before it closes.',
        'A quick mind makes the pass cleaner.',
        'If it goes wide, attack again.',
        'Let the clue be your winger.',
        'Small space is enough for a goal.',
        'You only need one clean move.',
        'The next card is a counterattack.',
        'Keep the tempo sunny and sharp.',
        'Spain loves a fearless finish.',
      ],
    },
    ru: {
      openings: [
        'Фланг открыт, можно ускоряться',
        'Трибуны чувствуют твое первое касание',
        'Смещайся в центр и доверься следующей букве',
        'Смелый дриблинг начинается с одной карточки',
        'Этот вопрос просит скорости',
        'Защитник моргнул, забирай коридор',
        'Ответ уже набирает разбег',
        'На правом фланге сегодня свободно',
        'Юная звезда не ждет слишком долго',
        'Матч просит смелого касания',
      ],
      endings: [
        'Сначала касание, потом рывок.',
        'Бей в свободную зону до закрытия.',
        'Быстрая мысль делает пас чище.',
        'Если мимо, атакуй снова.',
        'Пусть подсказка станет твоим вингером.',
        'Малого пространства хватит для гола.',
        'Нужен всего один чистый ход.',
        'Следующая карточка это контратака.',
        'Держи темп солнечным и острым.',
        'Испания любит бесстрашный финиш.',
      ],
    },
    es: {
      openings: [
        'La banda esta abierta, acelera ahora',
        'La grada siente tu primer toque',
        'Recorta hacia dentro y confia en la letra',
        'Un regate valiente empieza con una tarjeta',
        'Esta pregunta pide velocidad',
        'El defensa parpadeo, toma el pasillo',
        'Tu respuesta ya esta corriendo',
        'La banda derecha tiene espacio hoy',
        'Una estrella joven no espera demasiado',
        'El partido pide un toque valiente',
      ],
      endings: [
        'Primero toque, luego carrera.',
        'Ataca el hueco antes de que cierre.',
        'Una mente rapida limpia el pase.',
        'Si sale fuera, ataca otra vez.',
        'Que la pista sea tu extremo.',
        'Poco espacio basta para gol.',
        'Solo necesitas un movimiento limpio.',
        'La siguiente tarjeta es contraataque.',
        'Mantén el ritmo soleado y afilado.',
        'Espana ama un final valiente.',
      ],
    },
    uk: {
      openings: [
        'Фланг відкритий, можна прискорюватися',
        'Трибуни відчувають твій перший дотик',
        'Зміщуйся в центр і довірся наступній літері',
        'Сміливий дриблінг починається з однієї картки',
        'Це запитання просить швидкості',
        'Захисник кліпнув, забирай коридор',
        'Відповідь уже набирає розгін',
        'На правому фланзі сьогодні є простір',
        'Молода зірка не чекає надто довго',
        'Матч просить сміливого дотику',
      ],
      endings: [
        'Спершу дотик, потім ривок.',
        'Бий у вільну зону, доки її не закрили.',
        'Швидка думка робить пас чистішим.',
        'Якщо повз, атакуй знову.',
        'Нехай підказка стане твоїм вінгером.',
        'Малого простору вистачить для гола.',
        'Потрібен лише один чистий хід.',
        'Наступна картка це контратака.',
        'Тримай темп сонячним і гострим.',
        'Іспанія любить безстрашний фініш.',
      ],
    },
  },
  trollMama: {
    en: {
      openings: [
        'Slow the midfield and look up',
        'The pass is hidden in the pause',
        'A calm touch opens the phrase',
        'Let the ball rest under your foot',
        'The answer needs a soft tempo',
        'One quiet second can win the move',
        'The sentence has a passing lane',
        'Control first, celebration later',
        'The stadium gets quiet for genius',
        'A perfect pause beats a rushed shot',
      ],
      endings: [
        'Find the pass before the shot.',
        'Let the clue breathe for one beat.',
        'A clean angle makes memory lighter.',
        'The best answer arrives between lines.',
        'Keep possession of the thought.',
        'Soft control is still control.',
        'The phrase opens when you stop forcing it.',
        'One measured pass is enough.',
        'The midfield belongs to patience.',
        'Calm feet make brave answers.',
      ],
    },
    ru: {
      openings: [
        'Замедли центр поля и подними голову',
        'Пас спрятан в паузе',
        'Спокойное касание открывает фразу',
        'Пусть мяч полежит под ногой',
        'Ответу нужен мягкий темп',
        'Одна тихая секунда может выиграть ход',
        'У предложения есть линия паса',
        'Сначала контроль, праздник потом',
        'Стадион затихает перед гением',
        'Идеальная пауза сильнее поспешного удара',
      ],
      endings: [
        'Найди пас раньше удара.',
        'Дай подсказке вдохнуть один такт.',
        'Чистый угол делает память легче.',
        'Лучший ответ приходит между линий.',
        'Сохрани владение мыслью.',
        'Мягкий контроль все равно контроль.',
        'Фраза откроется, когда ты перестанешь давить.',
        'Одного выверенного паса достаточно.',
        'Центр поля принадлежит терпению.',
        'Спокойные ноги делают ответы смелыми.',
      ],
    },
    es: {
      openings: [
        'Baja el ritmo del centro y mira arriba',
        'El pase se esconde en la pausa',
        'Un toque tranquilo abre la frase',
        'Deja el balon bajo el pie',
        'La respuesta necesita tempo suave',
        'Un segundo quieto puede ganar la jugada',
        'La frase tiene linea de pase',
        'Primero control, luego fiesta',
        'El estadio calla ante el genio',
        'Una pausa perfecta gana a un tiro apresurado',
      ],
      endings: [
        'Encuentra el pase antes del tiro.',
        'Deja respirar la pista un compas.',
        'Un angulo limpio aligera la memoria.',
        'La mejor respuesta llega entre lineas.',
        'Conserva la posesion del pensamiento.',
        'El control suave sigue siendo control.',
        'La frase abre cuando dejas de forzar.',
        'Un pase medido basta.',
        'El centro pertenece a la paciencia.',
        'Pies tranquilos hacen respuestas valientes.',
      ],
    },
    uk: {
      openings: [
        'Сповільни центр поля й підніми голову',
        'Пас схований у паузі',
        'Спокійний дотик відкриває фразу',
        'Нехай мʼяч полежить під ногою',
        'Відповіді потрібен мʼякий темп',
        'Одна тиха секунда може виграти хід',
        'У речення є лінія пасу',
        'Спершу контроль, святкування потім',
        'Стадіон стихає перед генієм',
        'Ідеальна пауза сильніша за поспішний удар',
      ],
      endings: [
        'Знайди пас раніше за удар.',
        'Дай підказці вдихнути один такт.',
        'Чистий кут робить памʼять легшою.',
        'Найкраща відповідь приходить між лініями.',
        'Збережи володіння думкою.',
        'Мʼякий контроль усе одно контроль.',
        'Фраза відкриється, коли ти перестанеш тиснути.',
        'Одного вивіреного пасу достатньо.',
        'Центр поля належить терпінню.',
        'Спокійні ноги роблять відповіді сміливими.',
      ],
    },
  },
  capeChampion: {
    en: {
      openings: [
        'Hold the line and watch the ball',
        'The penalty moment is calmer than it looks',
        'A clean save starts with still eyes',
        'The goalmouth is yours for this card',
        'Pressure is just crowd noise',
        'Set your gloves before the answer',
        'A keeper reads the shot early',
        'The line is safe if you breathe',
        'This prompt is a stoppage-time save',
        'Stay tall until the ball moves',
      ],
      endings: [
        'Catch the mistake before it crosses the line.',
        'A save can be quiet and perfect.',
        'Let the clue come to your hands.',
        'Wrong answers still show the shooting angle.',
        'Protect the streak with one clean choice.',
        'Do not dive before the letter moves.',
        'The next card needs your calm.',
        'A goalkeeper wins by seeing early.',
        'Stand firm and make the memory save.',
        'Spain builds from the back.',
      ],
    },
    ru: {
      openings: [
        'Держи линию и смотри на мяч',
        'Пенальти спокойнее, чем кажется',
        'Чистый сейв начинается с неподвижных глаз',
        'Эти ворота твои на эту карточку',
        'Давление это всего лишь шум трибун',
        'Поставь перчатки перед ответом',
        'Вратарь читает удар заранее',
        'Линия в безопасности, если ты дышишь',
        'Этот вопрос как сейв в добавленное время',
        'Стой высоко, пока мяч не пошел',
      ],
      endings: [
        'Поймай ошибку до линии ворот.',
        'Сейв может быть тихим и идеальным.',
        'Пусть подсказка прилетит в руки.',
        'Неверный ответ тоже показывает угол удара.',
        'Защити серию одним чистым выбором.',
        'Не прыгай раньше движения буквы.',
        'Следующей карточке нужно твое спокойствие.',
        'Вратарь выигрывает ранним чтением.',
        'Стой крепко и делай сейв памяти.',
        'Испания начинает атаки от своих ворот.',
      ],
    },
    es: {
      openings: [
        'Mantén la linea y mira el balon',
        'El penalti esta mas tranquilo de lo que parece',
        'Una parada limpia empieza con ojos quietos',
        'La porteria es tuya en esta tarjeta',
        'La presion solo es ruido de grada',
        'Coloca los guantes antes de responder',
        'Un portero lee el tiro temprano',
        'La linea esta segura si respiras',
        'Esta pregunta es parada en el descuento',
        'Quédate alto hasta que el balon se mueva',
      ],
      endings: [
        'Atrapa el error antes de la linea.',
        'Una parada puede ser silenciosa y perfecta.',
        'Deja que la pista llegue a tus manos.',
        'Una respuesta mala tambien muestra el angulo.',
        'Protege la racha con una eleccion limpia.',
        'No saltes antes de que se mueva la letra.',
        'La siguiente tarjeta necesita tu calma.',
        'Un portero gana viendo antes.',
        'Mantente firme y salva la memoria.',
        'Espana construye desde atras.',
      ],
    },
    uk: {
      openings: [
        'Тримай лінію й дивися на мʼяч',
        'Пенальті спокійніше, ніж здається',
        'Чистий сейв починається з нерухомих очей',
        'Ці ворота твої на цю картку',
        'Тиск це лише шум трибун',
        'Постав рукавиці перед відповіддю',
        'Воротар читає удар заздалегідь',
        'Лінія в безпеці, якщо ти дихаєш',
        'Це запитання як сейв у доданий час',
        'Стій високо, доки мʼяч не пішов',
      ],
      endings: [
        'Спіймай помилку до лінії воріт.',
        'Сейв може бути тихим та ідеальним.',
        'Нехай підказка прилетить у руки.',
        'Неправильна відповідь теж показує кут удару.',
        'Захисти серію одним чистим вибором.',
        'Не стрибай раніше руху літери.',
        'Наступній картці потрібен твій спокій.',
        'Воротар виграє раннім читанням.',
        'Стій міцно й роби сейв памʼяті.',
        'Іспанія починає атаки від своїх воріт.',
      ],
    },
  },
  greenPower: {
    en: {
      openings: [
        'Captain mode is on until the whistle',
        'This word wants a firm tackle',
        'The air belongs to your header',
        'A long answer can be won in pieces',
        'The midfield duel starts now',
        'Stoppage time is still time',
        'The card is strong, but so are you',
        'Take the duel and keep balance',
        'A captain never leaves the rebound',
        'The set piece is waiting',
      ],
      endings: [
        'Win the first contact.',
        'Break the answer into tackles.',
        'A late goal still counts.',
        'Put your head through the hard letters.',
        'Hold the shape and clear the danger.',
        'One strong chunk opens the rest.',
        'Do not let the card bully the match.',
        'The rebound is yours if you stay ready.',
        'Structure wins the aerial duel.',
        'Spain fights until the final touch.',
      ],
    },
    ru: {
      openings: [
        'Режим капитана включен до свистка',
        'Этому слову нужен жесткий подкат',
        'Верховой мяч твой',
        'Длинный ответ можно выиграть по частям',
        'Битва в центре начинается сейчас',
        'Добавленное время тоже время',
        'Карточка сильная, но ты тоже',
        'Принимай дуэль и держи равновесие',
        'Капитан не бросает отскок',
        'Стандарт уже ждет',
      ],
      endings: [
        'Выиграй первое единоборство.',
        'Разбей ответ на подкаты.',
        'Поздний гол тоже считается.',
        'Иди головой через тяжелые буквы.',
        'Держи форму и выноси опасность.',
        'Один сильный кусок откроет остальные.',
        'Не давай карточке командовать матчем.',
        'Отскок твой, если ты готов.',
        'Структура выигрывает верховую дуэль.',
        'Испания борется до последнего касания.',
      ],
    },
    es: {
      openings: [
        'Modo capitan hasta el silbato',
        'Esta palabra pide una entrada firme',
        'El balon aereo es tuyo',
        'Una respuesta larga se gana por partes',
        'El duelo del centro empieza ahora',
        'El descuento tambien es tiempo',
        'La tarjeta es fuerte, pero tu tambien',
        'Acepta el duelo y mantén equilibrio',
        'Un capitan no abandona el rebote',
        'La jugada a balon parado espera',
      ],
      endings: [
        'Gana el primer contacto.',
        'Divide la respuesta en entradas.',
        'Un gol tarde tambien cuenta.',
        'Mete la cabeza entre letras duras.',
        'Mantén la forma y despeja el peligro.',
        'Un bloque fuerte abre el resto.',
        'No dejes que la tarjeta mande el partido.',
        'El rebote es tuyo si estas listo.',
        'La estructura gana el duelo aereo.',
        'Espana pelea hasta el ultimo toque.',
      ],
    },
    uk: {
      openings: [
        'Режим капітана увімкнено до свистка',
        'Цьому слову потрібен жорсткий підкат',
        'Верховий мʼяч твій',
        'Довгу відповідь можна виграти частинами',
        'Битва в центрі починається зараз',
        'Доданий час теж час',
        'Картка сильна, але ти теж',
        'Приймай дуель і тримай рівновагу',
        'Капітан не кидає відскок',
        'Стандарт уже чекає',
      ],
      endings: [
        'Виграй перше єдиноборство.',
        'Розбий відповідь на підкати.',
        'Пізній гол теж зараховується.',
        'Іди головою крізь важкі літери.',
        'Тримай форму й винось небезпеку.',
        'Один сильний шматок відкриє решту.',
        'Не давай картці командувати матчем.',
        'Відскок твій, якщо ти готовий.',
        'Структура виграє верхову дуель.',
        'Іспанія бореться до останнього дотику.',
      ],
    },
  },
  webRunner: {
    en: {
      openings: [
        'The triangle is already forming',
        'One pass opens two memories',
        'Look for the root before the run',
        'The word has a teammate nearby',
        'Tiki-taka starts with a tiny link',
        'A false friend is pressing high',
        'The answer is between the lines',
        'A short pass can move the whole team',
        'The pattern is calling for possession',
        'The next clue wants a one-two',
      ],
      endings: [
        'Play the simple pass.',
        'Let the nearby card receive it.',
        'Possession makes the answer visible.',
        'Check the shirt before trusting the face.',
        'A one-two can unlock the clue.',
        'Do not force the vertical ball.',
        'The safest route may be diagonal.',
        'Let the team shape help quietly.',
        'One exact link builds the attack.',
        'Spain keeps the ball until space appears.',
      ],
    },
    ru: {
      openings: [
        'Треугольник уже складывается',
        'Один пас открывает две памяти',
        'Смотри на корень до рывка',
        'У слова рядом есть партнер',
        'Тики-така начинается с маленькой связи',
        'Ложный друг высоко прессингует',
        'Ответ находится между линий',
        'Короткий пас двигает всю команду',
        'Паттерн просит владения',
        'Следующая подсказка хочет стеночку',
      ],
      endings: [
        'Играй простой пас.',
        'Пусть соседняя карточка примет мяч.',
        'Владение делает ответ видимым.',
        'Проверь футболку перед доверием лицу.',
        'Стеночка может открыть подсказку.',
        'Не форсируй вертикальный пас.',
        'Самый безопасный маршрут может быть диагональным.',
        'Пусть командная форма тихо поможет.',
        'Одна точная связь строит атаку.',
        'Испания держит мяч, пока не появится пространство.',
      ],
    },
    es: {
      openings: [
        'El triangulo ya se forma',
        'Un pase abre dos memorias',
        'Mira la raiz antes de correr',
        'La palabra tiene companero cerca',
        'El tiki-taka empieza con enlace pequeno',
        'Un falso amigo presiona arriba',
        'La respuesta esta entre lineas',
        'Un pase corto mueve todo el equipo',
        'El patron pide posesion',
        'La siguiente pista quiere pared',
      ],
      endings: [
        'Juega el pase simple.',
        'Deja que la tarjeta cercana reciba.',
        'La posesion hace visible la respuesta.',
        'Comprueba la camiseta antes de confiar en la cara.',
        'Una pared puede abrir la pista.',
        'No fuerces el pase vertical.',
        'La ruta segura puede ser diagonal.',
        'Deja que la forma del equipo ayude.',
        'Un enlace exacto construye el ataque.',
        'Espana guarda el balon hasta que sale espacio.',
      ],
    },
    uk: {
      openings: [
        'Трикутник уже складається',
        'Один пас відкриває дві памʼяті',
        'Дивися на корінь до ривка',
        'У слова поруч є партнер',
        'Тікі-така починається з маленького звʼязку',
        'Хибний друг високо пресингує',
        'Відповідь знаходиться між лініями',
        'Короткий пас рухає всю команду',
        'Патерн просить володіння',
        'Наступна підказка хоче стіночку',
      ],
      endings: [
        'Грай простий пас.',
        'Нехай сусідня картка прийме мʼяч.',
        'Володіння робить відповідь видимою.',
        'Перевір футболку, перш ніж довіряти обличчю.',
        'Стіночка може відкрити підказку.',
        'Не форсуй вертикальний пас.',
        'Найбезпечніший маршрут може бути діагональним.',
        'Нехай командна форма тихо допоможе.',
        'Один точний звʼязок будує атаку.',
        'Іспанія тримає мʼяч, доки не зʼявиться простір.',
      ],
    },
  },
};

export const coachThoughts: Record<
  AssistantId,
  Record<SupportedLanguage, string[]>
> = Object.fromEntries(
  Object.entries(thoughtSources).map(([assistantId, byLanguage]) => [
    assistantId,
    Object.fromEntries(
      supportedLanguages.map((language) => {
        const source = byLanguage[language];
        return [
          language,
          buildThoughts(source.openings, source.endings),
        ];
      }),
    ),
  ]),
) as Record<AssistantId, Record<SupportedLanguage, string[]>>;

export function getCoachThought(
  interfaceLanguage: SupportedLanguage,
  seed: number,
  assistantId: AssistantId | string | undefined = defaultAssistantId,
  worldId: WorldId = 'football',
): string {
  const resolvedAssistantId = resolveAssistantId(assistantId, worldId);
  const thoughts =
    worldId === 'forest'
      ? forestCoachThoughts[resolvedAssistantId][interfaceLanguage]
      : coachThoughts[resolvedAssistantId][interfaceLanguage];
  return thoughts[Math.abs(Math.trunc(seed)) % thoughts.length];
}

const forestCoachThoughts: Record<AssistantId, Record<SupportedLanguage, string[]>> = {
  studyTroll: makeForestThoughts({
    en: ['A fresh leaf remembers softly', 'The path is small, but it is yours'],
    ru: ['Свежий лист помнит мягко', 'Тропа маленькая, зато твоя'],
    es: ['Una hoja fresca recuerda suave', 'El sendero es pequeno, pero es tuyo'],
    uk: ['Свіжий листок памʼятає мʼяко', 'Стежка маленька, зате твоя'],
  }),
  trollMama: makeForestThoughts({
    en: ['Warm tea, tidy clue, calm answer', 'Memory likes a clean table'],
    ru: ['Теплый чай, ровная подсказка, спокойный ответ', 'Память любит чистый стол'],
    es: ['Te tibio, pista clara, respuesta tranquila', 'La memoria quiere mesa limpia'],
    uk: ['Теплий чай, рівна підказка, спокійна відповідь', 'Памʼять любить чистий стіл'],
  }),
  capeChampion: makeForestThoughts({
    en: ['Context lights the forest trail', 'A small clue can save the mission'],
    ru: ['Контекст освещает лесную тропу', 'Маленькая подсказка спасает миссию'],
    es: ['El contexto ilumina el sendero', 'Una pista pequena salva la mision'],
    uk: ['Контекст освітлює лісову стежку', 'Маленька підказка рятує місію'],
  }),
  greenPower: makeForestThoughts({
    en: ['Break the word into friendly logs', 'Strong memory still walks gently'],
    ru: ['Разломи слово на дружелюбные поленья', 'Сильная память все равно идет мягко'],
    es: ['Parte la palabra en troncos amables', 'La memoria fuerte tambien pisa suave'],
    uk: ['Розділи слово на дружні поліна', 'Сильна памʼять усе одно йде мʼяко'],
  }),
  webRunner: makeForestThoughts({
    en: ['Every word leaves a silver thread', 'Follow the web, not the panic'],
    ru: ['Каждое слово оставляет серебряную нить', 'Следуй за сетью, а не за паникой'],
    es: ['Cada palabra deja un hilo plateado', 'Sigue la red, no el panico'],
    uk: ['Кожне слово залишає срібну нитку', 'Йди за мережею, а не за панікою'],
  }),
};

function makeForestThoughts(
  values: Record<SupportedLanguage, string[]>,
): Record<SupportedLanguage, string[]> {
  return Object.fromEntries(
    Object.entries(values).map(([language, thoughts]) => [
      language,
      thoughts.map(ensurePeriod),
    ]),
  ) as Record<SupportedLanguage, string[]>;
}

function buildThoughts(openings: string[], endings: string[]): string[] {
  return [...openings, ...endings].map(ensurePeriod);
}

function ensurePeriod(value: string): string {
  return value.endsWith('.') ? value : `${value}.`;
}
